import Link from "next/link";
import "./globals.css";

// metadata -> 얘는 서버 컴포넌트에서 사용가능
export const metadata = {
  title: "Web tutorial",
  description: "Generated by pks",
};

export default async function RootLayout({ children }) {
  //서버 컴포넌트에서 useState, useEffect 불가 -> 이걸 client 컴포넌트로 바꾸려면 맨 위에 "use client" 적으면 된다
  const resp = await fetch("http://localhost:9999/topics", {
    cache: "no-store",
  });
  // 캐쉬를 no store 저장 안한다 -> 효율은 떨어지지만 간단한 코드에선 데이터 바뀔때마다 재 랜더링
  // router.refresh()했을 때 캐쉬가 없으면 새롭게 데이터 받아온다.
  // Revalidation을 이용하면 캐쉬 가진것과 아닌것과 구분해서 가능 -> 추후에 공부
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">HOME</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">create</Link>
          </li>
          <li>
            <Link href="/update/1">update</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
